### ISSUE TITLE
vagrant up not work

### ISSUE THREAD

**Issue by nvcken** [marknotfound/node-mongo-vagrant#2]
after I run "vagrant up" ( on windows OS)
Log show 
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
GuestAdditions 4.3.12 running --- OK.
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant

then nothing run server.js

**Comment by maaixprt** [comment]
Here is issue with me. 

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'precise64' (v0) for provider: virtualbox
    default: Downloading: http://files.vagrantup.com/precise64.box
    default: Download redirected to host: hashicorp-files.hashicorp.com
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out

```

**Comment by flik** [comment]
same issue here as above...

**Comment by flik** [comment]
Anyone fixed that issue ?

**Comment by marknotfound** [comment]
@flik This repo is no longer maintained and very out of date. I strongly recommend using a newer image or migrating to docker if possible. This box runs on a version of Ubuntu that reached end of life 4 years ago. Consider this a more modern alternative: https://medium.com/zenofai/how-to-build-a-node-js-and-mongodb-application-with-docker-containers-15e535baabf5
